version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # MinIO API Port
      - "9001:9001" # MinIO Console Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lakehouse_network
    restart: unless-stopped

volumes:
  minio_data:

networks:
  lakehouse_network:
    external: true